m

diff --git a/tools/build_strap b/tools/build_strap
--- a/tools/build_strap
+++ b/tools/build_strap
@@ -28,7 +28,7 @@
 # true if the user specified non-default compilers.
 #
 
-usage="$0 [-l | -a adjunct.tar [-f] [-j maxjobs] [-u | -d protodir]]"
+usage="$0 [-l | -a adjunct.tar [-f] [-j maxjobs] [-c | -d protodir]]"
 wsroot=$(cd $(dirname $0)/../; pwd)
 pkgin_file="/opt/local/etc/pkgin/repositories.conf"
 manta_host="https://us-east.manta.joyent.com"
@@ -41,7 +41,7 @@ protodir=""
 max_jobs="128"
 force_build="no"
 report_loc="no"
-upload="no"
+create_cache="no"
 
 function fatal
 {
@@ -141,13 +141,12 @@ function download
 }
 
 #
-# Do a strap build into the cache directory, then upload the tarball into the
-# cache location.
+# Do a strap build into the cache directory, then create the tarball for
+# uploading.
 #
-function upload_strap
+function create_cache
 {
 	local cache_dir="$1"
-	local mdir="$2"
 
 	if [[ "$force_build" = "no" ]]; then
 		if [[ -d "$cache_dir" ]]; then
@@ -164,11 +163,11 @@ function upload_strap
 	mkdir -p $wsroot/output/
 
 	gtar -C "$cache_dir" -czf $wsroot/output/proto.strap.tgz . || {
-		echo "Failed to upload tarball" >&2
+		echo "Failed to create tarball" >&2
 		exit 1
 	}
 
-	echo "Uploaded $manta_host/$mdir"
+	echo "Created $wsroot/output/proto.strap.tgz"
 }
 
 #
@@ -185,10 +184,8 @@ function populate_strap
 		fatal "found weird non-directory $cache_dir"
 	fi
 
-	if [[ "$upload" = "yes" ]]; then
-		local dir="$manta_dir/$pkgsrc_branch/$srcdirsha/proto.strap.tgz.jlevon"
-
-		upload_strap $cache_dir $dir
+	if [[ "$create_cache" = "yes" ]]; then
+		create_cache $cache_dir
 		return
 	fi
 
@@ -222,10 +219,12 @@ function populate_strap
 export PATH=/usr/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin
 set -o pipefail
 
-while getopts "a:d:fhlj:u" arg; do
+while getopts "a:cd:fhlj:" arg; do
 	case $arg in
 	a)
 		adjunct=$OPTARG ;;
+	c)
+		create_cache="yes" ;;
 	d)
 		protodir=$OPTARG ;;
 	f)
@@ -237,8 +236,6 @@ while getopts "a:d:fhlj:u" arg; do
 		max_jobs=$OPTARG ;;
 	l)
 		report_loc="yes" ;;
-	u)
-		upload="yes" ;;
 	?)
 		echo "$usage" >&2
 		exit 1 ;;
@@ -254,7 +251,7 @@ fi
 [[ -d "$srcdir" ]] || fatal "cannot find illumos-extra in $srcdir"
 [[ -d "$srcdir/.git" ]] || fatal "$srcdir is not a git repo"
 
-if [[ "$upload" = "yes" ]]; then
+if [[ "$create_cache" = "yes" ]]; then
 	[[ -z "$protodir" ]] || fatal "can't specify -u and -d"
 else
 	[[ -n "$protodir" ]] || fatal "missing -d argument"
